version: '3.1'
services:
  stat-server:
    build: ./stat-service/server
    image: stat-service
    container_name: stat-service
    ports:
      - "9090:9090"
      - "9091:9091"

    depends_on:
      - statdb
    environment:
      - DATASOURCE_URL=jdbc:postgresql://statdb:5432/statdb
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres
      - SERVER_PORT=9090

  statdb:
    image: postgres:16.1
    volumes:
      - /var/lib/postgresql/data/
    container_name: statdb

    environment:
      - POSTGRES_DB=statdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10


  main-service:
    build: ./main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
      - "8081:8081"

    depends_on:
      - ewmdb
      - stat-server
    environment:
      - BASE_CLIENT_URL=http://stats-server:9090
      - DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main_db
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres
      - SERVER_PORT=8080

  ewmdb:
    image: postgres:16.1
    volumes:
      - /var/lib/postgresql/data/
    container_name: ewmdb
    environment:
      - POSTGRES_DB=ewmdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
        test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
        timeout: 5s
        interval: 5s
        retries: 10
volumes:
  stats_volume:
  main_volume:
